#!/usr/bin/env python3
"""
Generate a GitLab child-pipeline YAML with one test job per starter kit.

Discovers the kits via the test runner's `--list-kits` (the single source of
truth: subdirectories of starter_kits/ with an mdaa.yaml) and emits one job per
kit. Each job invokes the runner scoped to that kit (`--kit <name>`), so the
kits run as independent, parallel CI jobs on separate runners — without any
per-kit npm/nx package or a hand-maintained job list.

The child jobs obtain the built workspace (node_modules, .nx) from the shared
pipeline cache (key feature-merge-build-$CI_COMMIT_REF_SLUG, populated by the
parent's feature_merge_build_test job with policy pull-push). Child pipelines
cannot `needs:`/`dependencies:` a parent job's artifacts, so the cache is the
hand-off mechanism — the child generator job therefore `needs:`
feature_merge_build_test in the parent so the cache exists before the child runs.

Usage (from repo root):
  python3 scripts/ci/generate_starter_kit_jobs.py > starter-kit-pipeline.yml

If no kits are discovered, a single no-op job is emitted so the child pipeline
is valid (an empty pipeline is a GitLab error).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Resolve repo paths relative to this script (scripts/ci/ -> repo root).
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
KITS_ROOT = REPO_ROOT / "starter_kits"
RUNNER_REL = "../scripts/test/test_starter_kit.py"  # relative to starter_kits/

# Base job config: large Kubernetes sizing (4 CPU / 8Gi — each job runs one
# kit's synths sequentially, so it does not need the 3xlarge the former single
# all-kits job used), the global image, and the global before_script (child
# pipelines do NOT inherit the parent's global image/before_script), plus a
# pull cache to warm node_modules/.nx when available.
HEADER = """\
# AUTO-GENERATED by scripts/ci/generate_starter_kit_jobs.py — do not edit.
# One job per starter kit; each self-filters to its affected modules and runs
# on its own runner (parallel, isolated).
#
# Child pipelines cannot pull a parent job's artifacts via `dependencies:`, and
# the GitLab `cache:` is best-effort (may miss). So each job bootstraps itself
# the same way the repo's bin/mdaa wrapper does: npm install, then build only
# the CLI (plus the @aws-mdaa/testing harness that jest loads). The MDAA CLI
# then builds each module it needs on demand at synth time
# (lerna run build --scope <module>). The shared cache (same key as
# feature_merge_build_test) is pulled when available to warm node_modules and
# the build caches; correctness does not depend on a cache hit.

image: ${BASE_IMAGE_TAG}

before_script:
  - sudo chown -R 1001:1001 "$CI_PROJECT_DIR"
  - git config advice.addIgnoredFile false
  - git config --global user.name "CICD"
  - git config --global user.email "ci@example.com"

.starter_kit_test_base:
  interruptible: true
  # Child-pipeline jobs must opt out of the default `only: [branches, tags]`,
  # which would exclude this MR-triggered child pipeline and make it empty. The
  # parent already gates on merge_requests before triggering, so always run here.
  rules:
    - when: always
  # Retry on infra failure only (these jobs are idempotent: fresh checkout +
  # install + synth into a temp dir, compared against committed baselines). A
  # real synth/baseline failure (script_failure) is NOT retried.
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - scheduler_failure
  tags:
    - arch:amd64
  cache:
    key: feature-merge-build-$CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
      - packages/**/node_modules/
      - .nx/
    policy: pull
  allow_failure: false
  variables:
    GIT_DEPTH: '0'
    JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION: '1'
    KUBERNETES_CPU_REQUEST: '4'
    KUBERNETES_CPU_LIMIT: '4'
    KUBERNETES_MEMORY_REQUEST: 8Gi
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 8Gi
"""

JOB_BLOCK = """\
sk_{kit}:
  extends: .starter_kit_test_base
  script:
    # Bootstrap like bin/mdaa: install deps, then build only the CLI plus the
    # @aws-mdaa/testing harness (jest loads its compiled lib). The CLI builds
    # every other module on demand at synth time. Compiled lib/ is gitignored
    # and parent-job artifacts aren't available to a child pipeline, so this
    # must not assume a prior build; a warm cache just makes it faster.
    - npm install --no-save --quiet
    - MDAA_BUILD_CODE_ONLY=true npx lerna run build --scope @aws-mdaa/cli --scope @aws-mdaa/testing --loglevel warn
    - cd starter_kits && python3 {runner} --kit {kit}
"""

NOOP_BLOCK = """\
image: ${BASE_IMAGE_TAG}

sk_no_kits:
  rules:
    - when: always
  tags:
    - arch:amd64
  variables:
    KUBERNETES_CPU_REQUEST: '1'
    KUBERNETES_CPU_LIMIT: '1'
  script:
    - echo "No starter kits discovered; nothing to test."
"""


def list_kits() -> list[str]:
    """Enumerate kit names via the runner's --list-kits (single source of truth)."""
    result = subprocess.run(
        [sys.executable, RUNNER_REL, "--list-kits"],
        cwd=str(KITS_ROOT),
        capture_output=True,
        text=True,
        check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def generate(kits: list[str]) -> str:
    """Render the child-pipeline YAML for the given kits."""
    if not kits:
        return NOOP_BLOCK
    parts = [HEADER, ""]
    for kit in kits:
        parts.append(JOB_BLOCK.format(kit=kit, runner=RUNNER_REL))
        parts.append("")
    return "\n".join(parts)


def main() -> None:
    kits = list_kits()
    # Status to stderr so stdout is pure YAML for the artifact.
    print(f"Discovered {len(kits)} starter kit(s): {', '.join(kits) or 'none'}", file=sys.stderr)
    sys.stdout.write(generate(kits))


if __name__ == "__main__":
    main()
