/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { rulesForTool } from '../manifest';
import { ProjectionFile, ProjectionResult, Rule } from '../types';

const CLAUDE_RULES_DIR = '.claude/rules';
const CLAUDE_ROOT_FILE = 'CLAUDE.md';
const CANONICAL_DIR = 'agent_rules';
const PREAMBLE = [
  '<!-- Auto-generated by @aws-mdaa/agent-rules. Do not edit by hand. -->',
  '<!-- Edit the canonical sources under agent_rules/ and regenerate. -->',
].join('\n');

/**
 * Project rules to Claude Code layout. Each file contains only metadata and
 * a reference to the canonical source — no content is inlined.
 *
 *   - `always`-scoped rules → `CLAUDE.md` with references to each rule
 *   - All other rules → `.claude/rules/<name>.md` with scope metadata
 */
export function projectClaude(rules: readonly Rule[]): ProjectionResult {
  const targets = rulesForTool(rules, 'claude');
  const alwaysRules = targets.filter(r => r.entry.scope === 'always');
  const otherRules = targets.filter(r => r.entry.scope !== 'always');

  const files: ProjectionFile[] = [];

  if (alwaysRules.length > 0) {
    const sections = alwaysRules.map(r => {
      const desc = r.entry.description ? `_${r.entry.description}_\n\n` : '';
      return `## ${r.entry.name}\n\n${desc}See [\`${r.entry.name}\`](${CANONICAL_DIR}/${r.entry.name}.md)`;
    });
    files.push({
      path: CLAUDE_ROOT_FILE,
      contents: `${PREAMBLE}\n\n# MDAA Agent Rules\n\n${sections.join('\n\n---\n\n')}\n`,
    });
  }

  for (const rule of otherRules) {
    const meta: string[] = [`scope: ${rule.entry.scope}`];
    if (rule.entry.description) meta.push(`description: ${rule.entry.description}`);
    if (rule.entry.globs && rule.entry.globs.length > 0) {
      meta.push(`globs: ${rule.entry.globs.join(', ')}`);
    }
    const header = `<!-- ${meta.join(' | ')} -->`;
    files.push({
      path: `${CLAUDE_RULES_DIR}/${rule.entry.name}.md`,
      contents: `${PREAMBLE}\n${header}\n\nSee [\`${rule.entry.name}\`](../../${CANONICAL_DIR}/${rule.entry.name}.md)\n`,
    });
  }

  return { tool: 'claude', files };
}
