/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { rulesForTool } from '../manifest';
import { ProjectionFile, ProjectionResult, Rule } from '../types';

const COPILOT_ROOT_FILE = '.github/copilot-instructions.md';
const COPILOT_INSTRUCTIONS_DIR = '.github/instructions';
const CANONICAL_DIR = 'packages/utilities/agent-rules/rules';
const PREAMBLE = '<!-- Auto-generated by @aws-mdaa/agent-rules. Do not edit by hand. -->';

function applyToFor(rule: Rule): string | undefined {
  if (rule.entry.scope === 'fileMatch' && rule.entry.globs && rule.entry.globs.length > 0) {
    return rule.entry.globs.join(',');
  }
  if (rule.entry.scope === 'always') {
    return '**';
  }
  return undefined;
}

/**
 * Project rules to Copilot layout. Each file contains only frontmatter and
 * a reference to the canonical source — no content is inlined.
 *
 *   - `always`-scope → `.github/copilot-instructions.md` with references
 *   - Others → `.github/instructions/<name>.instructions.md`
 */
export function projectCopilot(rules: readonly Rule[]): ProjectionResult {
  const targets = rulesForTool(rules, 'copilot');
  const alwaysRules = targets.filter(r => r.entry.scope === 'always');
  const otherRules = targets.filter(r => r.entry.scope !== 'always');

  const files: ProjectionFile[] = [];

  if (alwaysRules.length > 0) {
    const sections = alwaysRules.map(
      r => `## ${r.entry.name}\n\nSee [\`${r.entry.name}\`](../${CANONICAL_DIR}/${r.entry.name}.md)`,
    );
    files.push({
      path: COPILOT_ROOT_FILE,
      contents: `${PREAMBLE}\n\n# MDAA Agent Rules\n\n${sections.join('\n\n---\n\n')}\n`,
    });
  }

  for (const rule of otherRules) {
    const apply = applyToFor(rule);
    const front: string[] = ['---'];
    if (apply) front.push(`applyTo: '${apply}'`);
    if (rule.entry.description) front.push(`description: ${rule.entry.description}`);
    front.push('---');

    files.push({
      path: `${COPILOT_INSTRUCTIONS_DIR}/${rule.entry.name}.instructions.md`,
      contents: `${front.join('\n')}\n\n${PREAMBLE}\n\nSee [\`${rule.entry.name}\`](../../${CANONICAL_DIR}/${rule.entry.name}.md)\n`,
    });
  }

  return { tool: 'copilot', files };
}
