/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { rulesForTool } from '../manifest';
import { ProjectionFile, ProjectionResult, Rule } from '../types';

const CURSOR_RULES_DIR = '.cursor/rules';
const CANONICAL_DIR = 'packages/utilities/agent-rules/rules';
const PREAMBLE = '<!-- Auto-generated by @aws-mdaa/agent-rules. Do not edit by hand. -->';

/**
 * Project rules to Cursor's `.mdc` format. Each file contains only
 * frontmatter and a reference to the canonical source.
 */
export function projectCursor(rules: readonly Rule[]): ProjectionResult {
  const targets = rulesForTool(rules, 'cursor');
  const files: ProjectionFile[] = targets.map(rule => {
    const front = [
      '---',
      ...(rule.entry.description ? [`description: ${rule.entry.description}`] : []),
      ...(rule.entry.globs && rule.entry.globs.length > 0 ? [`globs: ${rule.entry.globs.join(',')}`] : []),
      `alwaysApply: ${rule.entry.scope === 'always'}`,
      '---',
    ];

    return {
      path: `${CURSOR_RULES_DIR}/${rule.entry.name}.mdc`,
      contents: `${front.join('\n')}\n\n${PREAMBLE}\n\nSee @${CANONICAL_DIR}/${rule.entry.name}.md\n`,
    };
  });
  return { tool: 'cursor', files };
}
