/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { rulesForTool } from '../manifest';
import { ProjectionFile, ProjectionResult, Rule, RuleScope } from '../types';

const WINDSURF_RULES_DIR = '.windsurf/rules';
const CANONICAL_DIR = 'agent_rules';
const PREAMBLE = '<!-- Auto-generated by @aws-mdaa/agent-rules. Do not edit by hand. -->';

function activationFor(scope: RuleScope): string {
  switch (scope) {
    case 'always':
      return 'always_on';
    case 'auto':
      return 'model_decision';
    case 'fileMatch':
      return 'glob';
    case 'manual':
    default:
      return 'manual';
  }
}

/**
 * Project rules to Windsurf's `.windsurf/rules/<name>.md` layout.
 * Each file contains only frontmatter and a reference to the canonical source.
 */
export function projectWindsurf(rules: readonly Rule[]): ProjectionResult {
  const targets = rulesForTool(rules, 'windsurf');
  const files: ProjectionFile[] = targets.map(rule => {
    const front: string[] = ['---'];
    front.push(`trigger: ${activationFor(rule.entry.scope)}`);
    if (rule.entry.description) front.push(`description: ${rule.entry.description}`);
    if (rule.entry.globs && rule.entry.globs.length > 0) {
      front.push(`globs: ${rule.entry.globs.join(',')}`);
    }
    front.push('---');

    return {
      path: `${WINDSURF_RULES_DIR}/${rule.entry.name}.md`,
      contents: `${front.join('\n')}\n\n${PREAMBLE}\n\nSee @${CANONICAL_DIR}/${rule.entry.name}.md\n`,
    };
  });
  return { tool: 'windsurf', files };
}
