/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Standardized resource type identifiers for custom naming implementations.
 * Used with withResourceType() to create naming instances that can inject
 * service-type abbreviations into resource names.
 *
 * The default MdaaDefaultResourceNaming ignores this value.
 */
export enum MdaaResourceType {
  S3_BUCKET = 's3',
  LAMBDA_FUNCTION = 'lambda',
  LAMBDA_LAYER = 'lambda-layer',
  IAM_ROLE = 'iam-role',
  IAM_POLICY = 'iam-policy',
  KMS_KEY = 'kms',
  DYNAMODB_TABLE = 'dynamodb',
  SQS_QUEUE = 'sqs',
  SNS_TOPIC = 'sns',
  GLUE_CRAWLER = 'glue-crawler',
  GLUE_JOB = 'glue-job',
  GLUE_SECURITY_CONFIG = 'glue-sec',
  DATABREW_DATASET = 'databrew-ds',
  DATABREW_JOB = 'databrew-job',
  DATABREW_PROJECT = 'databrew-proj',
  DATABREW_RECIPE = 'databrew-recipe',
  DATABREW_RULESET = 'databrew-ruleset',
  DATABREW_SCHEDULE = 'databrew-schedule',
  ATHENA_WORKGROUP = 'athena',
  REDSHIFT_CLUSTER = 'redshift',
  REDSHIFT_PARAMETER_GROUP = 'redshift-pg',
  OPENSEARCH_DOMAIN = 'opensearch',
  OPENSEARCH_SERVERLESS = 'aoss',
  SAGEMAKER_DOMAIN = 'sagemaker',
  SAGEMAKER_NOTEBOOK = 'sagemaker-nb',
  SAGEMAKER_LIFECYCLE_CONFIG = 'sagemaker-lc',
  SAGEMAKER_PROJECT = 'sagemaker-proj',
  SAGEMAKER_GROUND_TRUTH = 'sagemaker-gt',
  SAGEMAKER_MODEL_MONITOR_SCHEDULE = 'sagemaker-mm-sched',
  SAGEMAKER_DATA_QUALITY_JOB_DEF = 'sagemaker-mm-dq',
  SAGEMAKER_MODEL_QUALITY_JOB_DEF = 'sagemaker-mm-mq',
  SAGEMAKER_MODEL_BIAS_JOB_DEF = 'sagemaker-mm-mb',
  SAGEMAKER_MODEL_EXPLAINABILITY_JOB_DEF = 'sagemaker-mm-me',
  EC2_INSTANCE = 'ec2',
  EC2_SECURITY_GROUP = 'sg',
  EC2_VOLUME = 'ebs',
  EC2_KEY_PAIR = 'ec2-key',
  ECS_CLUSTER = 'ecs',
  ECS_FARGATE = 'ecs-fargate',
  ECS_CONTAINER = 'ecs-container',
  EKS_CLUSTER = 'eks',
  RDS_CLUSTER = 'rds',
  DMS_REPLICATION_INSTANCE = 'dms-ri',
  DMS_REPLICATION_TASK = 'dms-task',
  DMS_SUBNET_GROUP = 'dms-sg',
  DMS_ENDPOINT = 'dms-ep',
  DATASYNC_AGENT = 'datasync',
  DATASYNC_TASK = 'datasync-task',
  DATAZONE_DOMAIN = 'datazone',
  DATAZONE_PROJECT = 'datazone-proj',
  DATAZONE_ENV = 'datazone-env',
  DATAZONE_DATASOURCE = 'datazone-ds',
  EVENTBRIDGE_BUS = 'eventbridge',
  EVENTBRIDGE_RULE = 'eventbridge-rule',
  QUICKSIGHT_DATASOURCE = 'quicksight',
  QUICKSIGHT_VPC_CONNECTION = 'quicksight-vpc',
  STEPFUNCTIONS = 'sfn',
  CLOUDWATCH_LOG_GROUP = 'logs',
  LOGS_DELIVERY_SOURCE = 'logs-src',
  LOGS_DELIVERY_DESTINATION = 'logs-dest',
  CUSTOM_RESOURCE = 'custom',
  BEDROCK_AGENT = 'bedrock-agent',
  BEDROCK_AGENTCORE_RUNTIME = 'agentcore-runtime',
  BEDROCK_AGENTCORE_ENDPOINT = 'agentcore-ep',
  BEDROCK_GUARDRAIL = 'bedrock-guardrail',
  BEDROCK_KNOWLEDGE_BASE = 'bedrock-kb',
  MLFLOW_TRACKING_SERVER = 'mlflow',
  SAGEMAKER_FEATURE_GROUP = 'sagemaker-fg',
  SAGEMAKER_ENDPOINT = 'sagemaker-ep',
  SAGEMAKER_MODEL_PACKAGE_GROUP = 'sagemaker-mpg',
  SAGEMAKER_PIPELINE = 'sagemaker-pipeline',
  CODECOMMIT_REPO = 'codecommit',
  CODEBUILD_PROJECT = 'codebuild',
  CODEPIPELINE = 'codepipeline',
  REDSHIFT_SCHEDULED_ACTION = 'redshift-sa',
  S3_STORAGE_LENS = 's3-storage-lens',
  GLUE_DATABASE = 'glue-db',
  GLUE_CONNECTION = 'glue-connection',
  GLUE_CLASSIFIER = 'glue-classifier',
  GLUE_WORKFLOW = 'glue-workflow',
  GLUE_TRIGGER = 'glue-trigger',
  EFS_FILESYSTEM = 'efs',
  SECRETS_MANAGER_SECRET = 'secret',
  ROUTE53_HOSTED_ZONE = 'route53',
  RAM_RESOURCE_SHARE = 'ram',
  IAM_SAML_PROVIDER = 'iam-saml',
  COGNITO_USER_POOL = 'cognito-up',
  COGNITO_USER_POOL_DOMAIN = 'cognito-domain',
  COGNITO_RESOURCE_SERVER = 'cognito-rs',
  COGNITO_USER_POOL_CLIENT = 'cognito-client',
  APIGATEWAY_REST_API = 'apigw',
  APIGATEWAY_AUTHORIZER = 'apigw-auth',
  WAF_IP_SET = 'waf-ipset',
  WAF_WEB_ACL = 'waf-acl',
}
