/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { MdaaRoleHelper } from '@aws-mdaa/iam-role-helper';
import { MdaaTestApp } from '@aws-mdaa/testing';
import { Template } from 'aws-cdk-lib/assertions';
import {
  GAIAL3Construct,
  GAIAL3ConstructProps,
  SupportedAuthTypes,
  SupportedRegion,
  SupportedSageMakerModels,
} from '../lib';
import * as fs from 'fs';

describe('MDAA Compliance Stack Tests', () => {
  const testApp = new MdaaTestApp();

  const roleHelper = new MdaaRoleHelper(testApp.testStack, testApp.naming);

  const constructProps: GAIAL3ConstructProps = {
    gaia: {
      dataAdminRoles: [
        {
          name: 'test-admin',
        },
      ],
      prefix: 'test',
      llms: {
        sagemaker: [
          {
            model: SupportedSageMakerModels.FALCON_LITE,
          },
          {
            model: SupportedSageMakerModels.MISTRAL7B_INSTRUCT2,
          },
          {
            model: SupportedSageMakerModels.LLAMA2_13B_CHAT,
          },
        ],
      },
      skipApiGatewayDefaultWaf: false,
      setApiGateWayAccountCloudwatchRole: true,
      api: {
        restApiDomainName: 'rest-api-domain',
        hostedZoneName: 'test',
        socketApiDomainName: 'socket-api-domain',
      },
      bedrock: {
        roleArn: 'arn:bedrockRole',
        enabled: true,
        region: SupportedRegion.US_EAST_1,
      },
      rag: {
        engines: {
          aurora: {
            minCapacity: 0.5,
            maxCapacity: 4,
          },
          kendra: {
            createIndex: true,
            external: [
              {
                kendraId: 'index-id',
                name: 'index-name',
                roleArn: 'arn:role-arn',
              },
              {
                kendraId: 'index-id',
                name: 'index-name',
                region: SupportedRegion.CA_CENTRAL_1,
              },
            ],
          },
          knowledgeBase: {
            external: [
              {
                kbId: 'kb-id',
                name: 'kb-test',
                roleArn: 'arn:role-arn',
              },
              {
                kbId: 'kb-id-2',
                name: 'kb-test-2',
                region: SupportedRegion.CA_CENTRAL_1,
              },
            ],
          },
        },
        embeddingsModels: [
          {
            provider: 'bedrock',
            name: 'amazon.titan-embed-text-v1',
            dimensions: 1536,
            isDefault: true,
          },
          {
            provider: 'openai',
            name: 'text-embedding-ada-002',
            dimensions: 1536,
          },
        ],
        crossEncoderModels: [],
      },
      concurrency: {
        restApiConcurrentLambdas: 2,
        modelInterfaceConcurrentLambdas: 2,
        websocketConcurrentLambdas: 2,
      },
      vpc: {
        vpcId: 'XXXXXXXX',
        appSubnets: ['subnet1'],
        appSecurityGroupId: 'sg-someappid123154',
        dataSubnets: ['subnet2'],
        dataSecurityGroupId: 'sg-somedataid1231354',
      },
      auth: {
        authType: SupportedAuthTypes.ACTIVE_DIRECTORY,
        cognitoDomain: 'some-unique-pool-domain-name',
        idpSamlMetadataUrlOrFileParamPath: '/some/path',
        idpSamlEmailClaimParamPath: '/some/other/path',
        oAuthRedirectUrl: 'example.com',
      },
    },
    roleHelper: roleHelper,
    naming: testApp.naming,
  };

  new GAIAL3Construct(testApp.testStack, 'teststack', constructProps);
  testApp.checkCdkNagCompliance(testApp.testStack, {
    // The BucketNotifications HandlerPolicy inline-policy findings are suppressed at the
    // construct (rag-engines/data-import/index.ts), so no path ignore is needed for them.
    // OverflowPolicy is a synth-time CDK resource that cannot be suppressed at construct time.
    ignorePathPatterns: ['OverflowPolicy'],
  });
  const template = Template.fromStack(testApp.testStack);

  fs.writeFileSync('./test/test-template.json', JSON.stringify(template, undefined, 2));

  // Verify the IAMNoInlinePolicy suppression on the upload bucket's notification handler
  // policy is present and scoped to BucketNotifications policies (not broadened to
  // arbitrary IAM policies), guarding against future refactors dropping or widening it.
  const IAM_NO_INLINE_POLICY_IDS = [
    'NIST.800.53.R5-IAMNoInlinePolicy',
    'HIPAA.Security-IAMNoInlinePolicy',
    'PCI.DSS.321-IAMNoInlinePolicy',
  ];

  // Distinctive reason text for the suppression added by this construct, used to
  // distinguish it from other pre-existing IAMNoInlinePolicy suppressions in GAIA.
  const UPLOAD_HANDLER_REASON_MARKER = 'auto-generated by the CDK bucket-notifications handler';

  const suppressions = (resource: { Metadata?: Record<string, unknown> }): { id: string; reason: string }[] => {
    const cdkNag = resource.Metadata?.['cdk_nag'] as
      | { rules_to_suppress?: { id: string; reason: string }[] }
      | undefined;
    return cdkNag?.rules_to_suppress ?? [];
  };

  const iamPolicies = template.findResources('AWS::IAM::Policy');

  test('upload bucket notification HandlerPolicy carries the IAMNoInlinePolicy suppressions', () => {
    const handlerPolicies = Object.entries(iamPolicies).filter(([logicalId]) =>
      logicalId.includes('UploadBucketNotificationsHandlerPolicy'),
    );
    expect(handlerPolicies).toHaveLength(1);
    const ids = suppressions(handlerPolicies[0][1]).map(s => s.id);
    IAM_NO_INLINE_POLICY_IDS.forEach(id => expect(ids).toContain(id));
  });

  test('this construct’s bucket-notifications suppression is not applied to unrelated policies', () => {
    // Only guard the suppression THIS construct adds (identified by its reason marker) —
    // other IAMNoInlinePolicy suppressions on CDK-managed policies are pre-existing and
    // out of scope. The marker suppression must land only on the notification handler policy.
    const withMarker = Object.entries(iamPolicies).filter(([, r]) =>
      suppressions(r).some(
        s => IAM_NO_INLINE_POLICY_IDS.includes(s.id) && s.reason.includes(UPLOAD_HANDLER_REASON_MARKER),
      ),
    );
    expect(withMarker.length).toBeGreaterThan(0);
    withMarker.forEach(([logicalId]) => expect(logicalId).toContain('UploadBucketNotificationsHandlerPolicy'));
  });
});
